pipeline: # Pipeline section, defines pipeline's properties
    mode: local # Running mode, local or docker, default local
    project_name: text_classifier # Name of the pipeline
    admin_token: EmDICTBF1ppONSciYVd03M9xkmF6hFqW
    user_name: AnalyticsTeam


modules:
    -   node: reader # Name of the module
        script: src/reader.py
        dependencies:
            -   data1
            -   data2
        params:
            -   name: mult
                type: float # Type of the param, int, float or collection
                start: 0.2
                end: 0.6
                step_size: 0.2
            -   name: add
                type: float # Type of the param, int, float or collection
                start: 1.0
                end: 2.0
                step_size: 0.5

    -   node: append1 # Name of the module
        script: src/append1.py
        params:
            -   name: num
                type: collection # Type of the param, int, float or collection
                values: # Possible vaules for collection param
                    - 1000
                    - 2000
                    - 5000

    -   node: append2 # Name of the module
        script: src/append2.py
        params:
            -   name: num
                type: collection # Type of the param, int, float or collection
                values: # Possible vaules for collection param
                    - -1000
                    - -2000
                    - -5000

    -   node: writer
        script: src/writer.py
        input_nodes: 
            -   append1
            -   append2
        params:
            -   name: subtract
                type: float
                start: -1.0
                end: 0.0
                step_size: 0.3

            -   name: classifier
                type: collection # Type of the param, int, float or collection
                values: # Possible vaules for collection param
                    - SVM
                    - NaiveBayes
                    - MLP
                    - DT
                    - KNN
                    - RandomForest
                    - Adaboost
                    - GradientBoost
