pipeline: # Pipeline section, defines pipeline's properties
    project_name: analytics_bayesian_1 # Name of the pipeline, cloud last run #29
    admin_token: EmDlCTBF1ppONSciYVd03M9xkmF6hFqW
    user_name: AnalyticsTeam


modules:
    -   node: reader # Name of the module
        script: src/reader.py
        dependencies:
            -   data1
            -   data2
        params:
            -   name: mult
                type: float # Type of the param, int, float or collection
                start: 0.2
                end: 0.4
                step_size: 0.1
            -   name: add
                type: float # Type of the param, int, float or collection
                start: 1.0
                end: 1.5
                step_size: 0.2

    -   node: append1 # Name of the module
        script: src/append1.py
        input_nodes:
            -   reader
        params:
            -   name: num
                type: float
                start: -1.0
                end: 1.0
                step_size: 1

    -   node: append2 # Name of the module
        script: src/append2.py
        input_nodes:
            -   reader
        params:
            -   name: num
                type: float
                start: -1.0
                end: 1.0
                step_size: 1

    -   node: writer
        script: src/writer.py
        input_nodes: 
            -   append1
            -   append2
        params:
            -   name: subtract
                type: float
                start: -1.0
                end: 1.0
                step_size: 1
        optimize:
            -   metric: sum_of_stuff
                direction: max # min | max
                search: bayesian # grid | bayesian (if bayesian, must be all float)
